(defpackage cl-polynomial/tests
  (:use #:cl #:fiveam)
  (:local-nicknames (#:u    #:cl-polynomial/util)
                    (#:p    #:cl-polynomial/polynomial)
                    (#:fpx  #:cl-polynomial/fpx)
                    (#:fp   #:cl-polynomial/fp)
                    (#:zx   #:cl-polynomial/zx)
                    (#:z    #:cl-polynomial/z)
                    (#:alex #:alexandria)
                    (#:si   #:stateless-iterators))
  (:export #:run-tests))
