name: CI tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install roswell
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Install Ultralisp
        run: |
          ros -e '(ql-dist:install-dist "http://dist.ultralisp.org/" :prompt nil)'
      - name: Get ASDF
        run: |
          curl https://common-lisp.net/project/asdf/archives/asdf.lisp -o $GITHUB_WORKSPACE/asdf.lisp
          cat $GITHUB_WORKSPACE/asdf.lisp
          cat $GITHUB_WORKSPACE/.sbclrc
          echo '(load $GITHUB_WORKSPACE/"asdf.lisp")' | cat - $GITHUB_WORKSPACE/.sbclrc > tmp
          mv tmp $GITHUB_WORKSPACE/.sbclrc
      - name: Run tests
        run: |
          ros -l $GITHUB_WORKSPACE/tests/ci.lisp
